const CONFIG={osrmUrl:'https://router.project-osrm.org/route/v1/driving',nominatimUrl:'https://nominatim.openstreetmap.org/search',defaultZoom:16,gpsOptions:{enableHighAccuracy:true,maximumAge:500},debounceMs:400,cameraAlertRange:0.5,cameraShowRange:2,cameraNearRange:0.03,preNotifyRange:0.5,speedWarnCooldown:8000,speechResumeInterval:3000,autoNightStart:20,autoNightEnd:7};
let map=L.map('map',{zoomControl:false,rotate:true,rotateControl:false}).setView([51.5,-0.09],5);L.control.zoom({position:'bottomright'}).addTo(map);
let userPos=null,destination=null,destinationName='',routeControl=null,userMarker=null,gpsCentered=false,navigationActive=false,lastLat=null,lastLng=null,lastTime=null,currentBearing=0,currentSpeed=0,routeInstructions=[],instructionIndex=0,totalRouteDist=0,routeCoords=[],lastSpokenIdx=-1,lastCameraSpoken=null,nearestCameraDistance=Infinity,routeType='fast',spoken500m=new Set(),spokenCameras500m=new Set(),routeLine=null,lastMapViewTime=0,lastMapViewPos=null,routePOIs=[],poiMarkers=[];
let speedAlertOver=10,speedAlertEnabled=true,voiceEnabled=true,isNightMode=true,roadEventsLoaded=false,mapTilesEnabled=true,avoidTolls=false,avoidFerries=false,avoidHighways=false,avoidUnpaved=false;
function saveSettings(){try{localStorage.setItem('naviSettings',JSON.stringify({routeType,speedAlertOver,speedAlertEnabled,voiceEnabled,isNightMode,mapTilesEnabled,avoidTolls,avoidFerries,avoidHighways,avoidUnpaved}))}catch(e){}}
function loadSettings(){try{const s=JSON.parse(localStorage.getItem('naviSettings'));if(s){if(s.routeType)routeType=s.routeType;if(s.speedAlertOver!==undefined)speedAlertOver=s.speedAlertOver;if(s.speedAlertEnabled!==undefined)speedAlertEnabled=s.speedAlertEnabled;if(s.voiceEnabled!==undefined)voiceEnabled=s.voiceEnabled;if(s.isNightMode!==undefined)isNightMode=s.isNightMode;if(s.mapTilesEnabled!==undefined)mapTilesEnabled=s.mapTilesEnabled;if(s.avoidTolls!==undefined)avoidTolls=s.avoidTolls;if(s.avoidFerries!==undefined)avoidFerries=s.avoidFerries;if(s.avoidHighways!==undefined)avoidHighways=s.avoidHighways;if(s.avoidUnpaved!==undefined)avoidUnpaved=s.avoidUnpaved}}catch(e){}}
loadSettings();
function calcBearing(a,b,c,d){const dl=(d-b)*Math.PI/180;const y=Math.sin(dl)*Math.cos(c*Math.PI/180);const x=Math.cos(a*Math.PI/180)*Math.sin(c*Math.PI/180)-Math.sin(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.cos(dl);return((Math.atan2(y,x)*180/Math.PI)+360)%360}
function calcSpeed(a,b,t,c,d,t2){const R=6371,dr=(c-a)*Math.PI/180,dl=(d-b)*Math.PI/180;const x=Math.sin(dr/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(dl/2)**2;const dist=2*R*Math.asin(Math.sqrt(x));const dt=(t2-t)/1000;return dt<0.5?0:dist/dt*3600}
function haversine(a,b,c,d){const R=6371,dr=(c-a)*Math.PI/180,dl=(d-b)*Math.PI/180;const x=Math.sin(dr/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function fmtDist(km){return km<1?Math.round(km*1000)+' m':km.toFixed(1)+' km'}
function fmtArrival(min){const d=new Date(Date.now()+min*60000);return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
function fmtDuration(min){const h=Math.floor(min/60);const m=Math.round(min%60);return h>0?h+'h '+m+'min':m+' min'}
function bearingName(b){const n=['na północ','na północny wschód','na wschód','na południowy wschód','na południe','na południowy zachód','na zachód','na północny zachód'];return n[Math.round(b/45)%8]}
const arrowChars=['⬆','↗','➡','↘','⬇','↙','⬅','↖'];
function bearingToArrow(b){return arrowChars[Math.round(b/45)%8]}
let displayedBearing=0;
function rotateMap(deg){let diff=deg-displayedBearing;if(diff>180)diff-=360;if(diff<-180)diff+=360;displayedBearing+=diff*0.25;if(displayedBearing>360)displayedBearing-=360;if(displayedBearing<0)displayedBearing+=360;document.getElementById('map').style.transform='rotate('+(-displayedBearing)+'deg)'}
function toggleVoice(){voiceEnabled=!voiceEnabled;document.getElementById('voiceToggle').classList.toggle('on',voiceEnabled);const sb=document.getElementById('btnSound');if(sb)sb.textContent=voiceEnabled?'🔊':'🔇';saveSettings()}
function speak(text){if(!voiceEnabled||!text)return;if(window.speechSynthesis.speaking)window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pl-PL';u.rate=1.05;u.volume=1;const t=document.getElementById('voiceToast');t.textContent=text;t.classList.add('show');u.onend=u.onerror=()=>t.classList.remove('show');window.speechSynthesis.speak(u)}
let speechUnlocked=false;function unlockSpeech(){if(speechUnlocked)return;speechUnlocked=true;try{const u=new SpeechSynthesisUtterance('');u.volume=0;u.rate=0.01;window.speechSynthesis.speak(u);window.speechSynthesis.cancel();window.speechSynthesis.resume()}catch(e){}}
document.addEventListener('touchstart',unlockSpeech,{once:true});document.addEventListener('click',unlockSpeech,{once:true});
setInterval(()=>{try{if(window.speechSynthesis&&!window.speechSynthesis.speaking)window.speechSynthesis.resume()}catch(e){}},CONFIG.speechResumeInterval);
let mapTilesLayer=null;
function loadMapTiles(){if(!mapTilesEnabled)return;if(mapTilesLayer)map.removeLayer(mapTilesLayer);mapTilesLayer=isNightMode?L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(map):L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:19}).addTo(map)}
loadMapTiles();
function toggleMapTiles(){mapTilesEnabled=!mapTilesEnabled;document.getElementById('mapTilesToggle').classList.toggle('on',mapTilesEnabled);if(mapTilesEnabled)loadMapTiles();else{if(mapTilesLayer){map.removeLayer(mapTilesLayer);mapTilesLayer=null}document.getElementById('map').style.background=isNightMode?'#111118':'#d8d8e0'}saveSettings()}
function toggleDayNight(){isNightMode=!isNightMode;document.body.classList.toggle('day-mode',!isNightMode);document.getElementById('dayNightToggle').classList.toggle('on',isNightMode);loadMapTiles();if(!mapTilesEnabled)document.getElementById('map').style.background=isNightMode?'#111118':'#d8d8e0';saveSettings()}
function autoDayNight(){const h=new Date().getHours();const shouldBeNight=h<CONFIG.autoNightEnd||h>=CONFIG.autoNightStart;if(shouldBeNight!==isNightMode)toggleDayNight()}
setInterval(autoDayNight,60000);
function createArrowIcon(bearing){return L.divIcon({className:'',html:'<svg class="user-arrow" viewBox="0 0 30 30" style="transform:rotate('+bearing+'deg)"><circle cx="15" cy="15" r="12" fill="#2979ff" stroke="white" stroke-width="2.5" opacity="0.95"/><polygon points="15,4 20,22 15,18 10,22" fill="white"/></svg>',iconSize:[30,30],iconAnchor:[15,15]})}
function openMainMenu(){document.getElementById('mainMenu').classList.add('open');document.getElementById('overlay').classList.add('show');document.getElementById('persistentMenu').style.display='none'}
function closeMainMenu(){document.getElementById('mainMenu').classList.remove('open');document.getElementById('overlay').classList.remove('show');if(!navigationActive)document.getElementById('persistentMenu').style.display='flex'}
function openSettingsSub(){document.getElementById('mainMenu').classList.remove('open');document.getElementById('ssTitle').textContent='Ustawienia trasy';document.getElementById('ssBody').innerHTML='<div class="ss-section"><h4>Typ trasy</h4><div class="route-types"><div class="route-type '+(routeType==='fast'?'active':'')+'" onclick="setRouteType(this,\'fast\')"><div class="rt-icon">⚡</div><div class="rt-label">Szybka</div></div><div class="route-type '+(routeType==='eco'?'active':'')+'" onclick="setRouteType(this,\'eco\')"><div class="rt-icon">🌿</div><div class="rt-label">Eko</div></div><div class="route-type '+(routeType==='short'?'active':'')+'" onclick="setRouteType(this,\'short\')"><div class="rt-icon">📏</div><div class="rt-label">Krótka</div></div></div></div><div class="ss-section"><h4>Unikaj</h4><div class="avoid-item"><div class="ai-left"><span class="ai-icon">💰</span> Opłaty</div><div class="toggle '+(avoidTolls?'on':'')+'" onclick="avoidTolls=!avoidTolls;this.classList.toggle(\'on\');saveSettings()"></div></div><div class="avoid-item"><div class="ai-left"><span class="ai-icon">🛤️</span> Drogi nieutwardzone</div><div class="toggle '+(avoidUnpaved?'on':'')+'" onclick="avoidUnpaved=!avoidUnpaved;this.classList.toggle(\'on\');saveSettings()"></div></div><div class="avoid-item"><div class="ai-left"><span class="ai-icon">🛣️</span> Autostrady</div><div class="toggle '+(avoidHighways?'on':'')+'" onclick="avoidHighways=!avoidHighways;this.classList.toggle(\'on\');saveSettings()"></div></div><div class="avoid-item"><div class="ai-left"><span class="ai-icon">⛴️</span> Promy</div><div class="toggle '+(avoidFerries?'on':'')+'" onclick="avoidFerries=!avoidFerries;this.classList.toggle(\'on\');saveSettings()"></div></div></div>';document.getElementById('settingsSub').classList.add('open')}
function openSpeedSettings(){document.getElementById('mainMenu').classList.remove('open');document.getElementById('ssTitle').textContent='Alerty prędkości';document.getElementById('ssBody').innerHTML='<div class="ss-section"><h4>Powiadomienia o przekroczeniu prędkości</h4><div class="ss-row"><label>Włącz alerty</label><div class="mm-toggle '+(speedAlertEnabled?'on':'')+'" onclick="speedAlertEnabled=!speedAlertEnabled;this.classList.toggle(\'on\');saveSettings()"></div></div><div class="ss-row"><label>Próg przekroczenia</label><div class="ss-val"><input type="range" min="1" max="30" value="'+speedAlertOver+'" oninput="speedAlertOver=parseInt(this.value);document.getElementById(\'speedAlertVal\').textContent=\'+\'+this.value+\' km/h\'"><span class="ss-num" id="speedAlertVal">+'+speedAlertOver+' km/h</span></div></div></div>';document.getElementById('settingsSub').classList.add('open')}
function closeSettingsSub(){document.getElementById('settingsSub').classList.remove('open');document.getElementById('mainMenu').classList.add('open');document.getElementById('overlay').classList.add('show')}
function setRouteType(el,type){document.querySelectorAll('.route-type').forEach(e=>e.classList.remove('active'));el.classList.add('active');routeType=type;saveSettings()}
function showLoading(msg){let el=document.getElementById('loadingOverlay');if(!el){el=document.createElement('div');el.id='loadingOverlay';el.style.cssText='position:fixed;top:0;left:0;right:0;bottom:0;z-index:1400;background:rgba(0,0,0,0.5);display:flex;align-items:center;justify-content:center;color:white;font-size:18px;font-weight:700;flex-direction:column;gap:12px';el.innerHTML='<div style="width:40px;height:40px;border:4px solid rgba(255,255,255,0.3);border-top-color:white;border-radius:50%;animation:spin 0.8s linear infinite"></div><span id="loadingText"></span><style>@keyframes spin{to{transform:rotate(360deg)}}</style>';document.body.appendChild(el)}document.getElementById('loadingText').textContent=msg||'Ładowanie...';el.style.display='flex'}
function hideLoading(){const el=document.getElementById('loadingOverlay');if(el)el.style.display='none'}
const speedCameras=[{lat:50.0614,lng:19.9366,limit:50,name:"Kraków centrum"},{lat:50.0412,lng:19.9734,limit:50,name:"Kraków Prokocim"},{lat:50.0710,lng:19.8930,limit:70,name:"Kraków Bronowice"},{lat:50.2556,lng:19.0240,limit:50,name:"Sosnowiec centrum"},{lat:51.1079,lng:17.0385,limit:50,name:"Wrocław centrum"},{lat:52.2297,lng:21.0122,limit:50,name:"Warszawa centrum"},{lat:52.2450,lng:21.0050,limit:50,name:"Warszawa Praga"},{lat:52.1780,lng:20.9680,limit:60,name:"Warszawa Ursynów"},{lat:51.7610,lng:19.4560,limit:50,name:"Łódź centrum"},{lat:54.3520,lng:18.6466,limit:50,name:"Gdańsk Oliwa"},{lat:50.6750,lng:17.9210,limit:60,name:"Opole centrum"},{lat:50.0410,lng:20.0050,limit:50,name:"Tarnów centrum"},{lat:51.2400,lng:22.5720,limit:50,name:"Lublin centrum"},{lat:52.4060,lng:16.9250,limit:50,name:"Poznań centrum"},{lat:50.8110,lng:19.1200,limit:50,name:"Częstochowa centrum"},{lat:50.4700,lng:19.0800,limit:140,name:"A1 Sieradz"},{lat:51.1500,lng:19.5000,limit:140,name:"A1 Radomsko"},{lat:51.8500,lng:19.3500,limit:140,name:"A1 Łódź"},{lat:52.7500,lng:18.9000,limit:140,name:"A1 Włocławek"},{lat:52.2800,lng:19.0500,limit:120,name:"A2 Łódź"},{lat:52.1500,lng:20.1000,limit:140,name:"A2 Warszawa"},{lat:50.0800,lng:19.5600,limit:140,name:"A4 Chrzanów"},{lat:50.2000,lng:20.8000,limit:140,name:"A4 Tarnów"},{lat:50.0000,lng:21.8000,limit:140,name:"A4 Rzeszów"},{lat:51.1500,lng:16.9800,limit:140,name:"A4 Wrocław"},{lat:50.7500,lng:17.1000,limit:140,name:"A4 Opole"}];
let routeCameras=[],currentSpeedLimit=0,lastSpeedWarnSpoken=0;
function distToRoute(lat,lng){if(!routeCoords.length)return Infinity;let minD=Infinity;for(let i=0;i<routeCoords.length-1;i+=3){const d=haversine(lat,lng,routeCoords[i].lat,routeCoords[i].lng);if(d<minD)minD=d;if(minD<0.1)return minD}return minD}
function loadRouteCameras(){if(!routeCoords.length)return;let minLat=90,maxLat=-90,minLng=180,maxLng=-180;for(const c of routeCoords){if(c.lat<minLat)minLat=c.lat;if(c.lat>maxLat)maxLat=c.lat;if(c.lng<minLng)minLng=c.lng;if(c.lng>maxLng)maxLng=c.lng}const margin=0.5;routeCameras=speedCameras.filter(cam=>cam.lat>=minLat-margin&&cam.lat<=maxLat+margin&&cam.lng>=minLng-margin&&cam.lng<=maxLng+margin&&distToRoute(cam.lat,cam.lng)<5);loadRoutePOIs(minLat,maxLat,minLng,maxLng,margin)}
const poiDatabase=[{lat:50.0625,lng:19.9415,type:'parking',name:'Parking Rynek'},{lat:50.0540,lng:19.9350,type:'fuel',name:'Orlen Kraków'},{lat:50.0680,lng:19.9520,type:'fuel',name:'BP Krowodrza'},{lat:50.0480,lng:19.9300,type:'parking',name:'Parking Kazimierz'},{lat:52.2297,lng:21.0122,type:'parking',name:'Parking Centrum WWA'},{lat:52.2350,lng:21.0050,type:'fuel',name:'Shell Warszawa'},{lat:52.2200,lng:21.0000,type:'traffic',name:'Korek Marszałkowska'},{lat:52.2400,lng:21.0100,type:'traffic',name:'Korek Jerozolimskie'},{lat:51.1079,lng:17.0385,type:'parking',name:'Parking Wrocław'},{lat:51.1050,lng:17.0250,type:'fuel',name:'Circle K Wrocław'},{lat:52.2150,lng:21.0200,type:'danger',name:'Roboty drogowe'},{lat:50.0600,lng:19.9400,type:'danger',name:'Zwężenie'},{lat:50.0750,lng:19.9200,type:'fuel',name:'Lotos Bronowice'},{lat:50.0400,lng:19.9700,type:'parking',name:'Parking Prokocim'},{lat:52.2500,lng:20.9900,type:'police',name:'Kontrola policja'},{lat:51.7500,lng:19.4600,type:'fuel',name:'Orlen Łódź'},{lat:54.3500,lng:18.6500,type:'fuel',name:'Shell Gdańsk'},{lat:50.6800,lng:17.9200,type:'fuel',name:'BP Opole'},{lat:52.4100,lng:16.9300,type:'fuel',name:'Orlen Poznań'},{lat:50.8100,lng:19.1200,type:'fuel',name:'Lotos Częstochowa'},{lat:50.0350,lng:20.0100,type:'fuel',name:'Shell Tarnów'},{lat:51.2400,lng:22.5700,type:'fuel',name:'BP Lublin'}];
const poiIcons={parking:'🅿️',fuel:'⛽',traffic:'🚗',danger:'⚠️',police:'👮'};
function loadRoutePOIs(minLat,maxLat,minLng,maxLng,margin){routePOIs=poiDatabase.filter(p=>p.lat>=minLat-margin&&p.lat<=maxLat+margin&&p.lng>=minLng-margin&&p.lng<=maxLng+margin&&distToRoute(p.lat,p.lng)<2);renderPOIMarkers()}
function renderPOIMarkers(){poiMarkers.forEach(m=>map.removeLayer(m));poiMarkers=[];for(const poi of routePOIs){const icon=L.divIcon({className:'',html:'<div style="font-size:22px;text-shadow:0 1px 4px rgba(0,0,0,0.5)">'+poiIcons[poi.type]+'</div>',iconSize:[24,24],iconAnchor:[12,12]});const m=L.marker([poi.lat,poi.lng],{icon}).addTo(map);m.bindTooltip(poi.name,{permanent:false,direction:'top',offset:[0,-8]});poiMarkers.push(m)}for(const cam of routeCameras){const icon=L.divIcon({className:'',html:'<div style="font-size:18px;text-shadow:0 1px 4px rgba(0,0,0,0.5)">📸</div>',iconSize:[20,20],iconAnchor:[10,10]});const m=L.marker([cam.lat,cam.lng],{icon}).addTo(map);m.bindTooltip(cam.name+' ('+cam.limit+' km/h)',{permanent:false,direction:'top',offset:[0,-8]});poiMarkers.push(m)}}
function checkSpeedCameras(lat,lng,speed){let minDist=Infinity,nearestCam=null;for(const cam of routeCameras){const d=haversine(lat,lng,cam.lat,cam.lng);if(d<minDist){minDist=d;nearestCam=cam}}const alert=document.getElementById('cameraAlert'),scRing=document.getElementById('scRing'),scLimit=document.getElementById('scLimit');nearestCameraDistance=minDist;if(nearestCam&&minDist<CONFIG.cameraShowRange){currentSpeedLimit=nearestCam.limit;document.getElementById('camDistText').textContent=fmtDist(minDist);document.getElementById('camSpeedText').textContent='Ograniczenie: '+nearestCam.limit+' km/h — '+nearestCam.name;scLimit.textContent=nearestCam.limit;scLimit.style.display='flex';if(minDist<=CONFIG.cameraAlertRange&&minDist>CONFIG.cameraNearRange){alert.classList.add('show');const camKey=nearestCam.name+Math.round(minDist*10);if(camKey!==lastCameraSpoken){lastCameraSpoken=camKey;speak('Uwaga, fotoradar, '+nearestCam.limit+' km/h, za '+fmtDist(minDist))}}else alert.classList.remove('show');if(speedAlertEnabled&&speed>nearestCam.limit+speedAlertOver){const now=Date.now();if(now-lastSpeedWarnSpoken>CONFIG.speedWarnCooldown){lastSpeedWarnSpoken=now;speak('Uwaga! Przekroczono prędkość o '+Math.round(speed-nearestCam.limit)+' kilometrów na godzinę!');document.getElementById('speedWarning').classList.add('show');setTimeout(()=>document.getElementById('speedWarning').classList.remove('show'),3000)}}}else{alert.classList.remove('show');currentSpeedLimit=0;scLimit.textContent='—'}if(currentSpeedLimit>0){if(speed>currentSpeedLimit+speedAlertOver)scRing.className='sc-ring over';else if(speed>currentSpeedLimit)scRing.className='sc-ring warn';else scRing.className='sc-ring'}else scRing.className='sc-ring'}
function updateRouteStrip(lat,lng){if(!routeCoords.length||!navigationActive)return;const track=document.getElementById('sbTrack'),progress=document.getElementById('sbProgress');let totalDist=0;const cumDists=[0];for(let i=1;i<routeCoords.length;i++){totalDist+=haversine(routeCoords[i-1].lat,routeCoords[i-1].lng,routeCoords[i].lat,routeCoords[i].lng);cumDists.push(totalDist)}if(totalDist===0)return;let minD=Infinity,closestIdx=0;for(let i=0;i<routeCoords.length;i++){const d=haversine(lat,lng,routeCoords[i].lat,routeCoords[i].lng);if(d<minD){minD=d;closestIdx=i}}const doneDist=cumDists[closestIdx];progress.style.height=Math.min(100,(doneDist/totalDist)*100)+'%';track.querySelectorAll('.sidebar-strip-marker').forEach(m=>m.remove());const lookAhead=5;for(const inst of routeInstructions){if(inst.index<closestIdx)continue;const instDist=haversine(lat,lng,inst.lat,inst.lng);if(instDist>lookAhead)continue;const topPx=(instDist/lookAhead)*track.clientHeight;const m=document.createElement('div');m.className='sidebar-strip-marker';m.style.top=topPx+'px';m.innerHTML='<div class="icon-dot turn">'+bearingToArrow(inst.bearing||0)+'</div>';track.appendChild(m)}for(const cam of routeCameras){const d=haversine(lat,lng,cam.lat,cam.lng);if(d>lookAhead)continue;const topPx=(d/lookAhead)*track.clientHeight;const m=document.createElement('div');m.className='sidebar-strip-marker';m.style.top=topPx+'px';m.innerHTML='<div class="icon-dot camera">📸</div>';track.appendChild(m)}for(const poi of routePOIs){const d=haversine(lat,lng,poi.lat,poi.lng);if(d>lookAhead)continue;const topPx=(d/lookAhead)*track.clientHeight;const m=document.createElement('div');m.className='sidebar-strip-marker';m.style.top=topPx+'px';m.innerHTML='<div class="icon-dot '+poi.type+'">'+poiIcons[poi.type]+'</div>';track.appendChild(m)}const um=document.createElement('div');um.className='sidebar-strip-marker';um.style.top=Math.min(100,(doneDist/totalDist)*100)+'%';um.innerHTML='<div class="icon-dot user">⬆</div>';track.appendChild(um)}
function debouncedSetView(pos){const now=Date.now();if(now-lastMapViewTime<CONFIG.debounceMs)return;if(lastMapViewPos&&haversine(pos.lat,pos.lng,lastMapViewPos.lat,lastMapViewPos.lng)<0.005)return;lastMapViewTime=now;lastMapViewPos=pos;map.setView(pos,CONFIG.defaultZoom)}
navigator.geolocation.watchPosition(pos=>{const lat=pos.coords.latitude,lng=pos.coords.longitude,heading=pos.coords.heading,now=Date.now();userPos=L.latLng(lat,lng);if(lastLat!==null&&lastLng!==null&&lastTime!==null){const dt=(now-lastTime)/1000;if(dt>0.3){const b=calcBearing(lastLat,lastLng,lat,lng);const s=calcSpeed(lastLat,lastLng,lastTime,lat,lng,now);currentSpeed=s;if(s>1.5)currentBearing=b;lastLat=lat;lastLng=lng;lastTime=now}}else{lastLat=lat;lastLng=lng;lastTime=now}if(heading&&!isNaN(heading)&&heading!==0)currentBearing=heading;if(!userMarker){userMarker=L.marker(userPos,{icon:createArrowIcon(currentBearing),zIndexOffset:1000}).addTo(map)}else{userMarker.setLatLng(userPos);userMarker.setIcon(createArrowIcon(currentBearing))}if(!gpsCentered){gpsCentered=true;map.setView(userPos,CONFIG.defaultZoom)}if(navigationActive){debouncedSetView(userPos);rotateMap(currentBearing);checkRouteProximity(lat,lng);checkSpeedCameras(lat,lng,currentSpeed);updateRouteStrip(lat,lng)}document.getElementById('scCurrent').textContent=Math.round(currentSpeed);document.getElementById('sbTime').textContent=new Date().getHours().toString().padStart(2,'0')+':'+new Date().getMinutes().toString().padStart(2,'0');if(navigationActive&&now-lastGeoTime>30000){lastGeoTime=now;reverseGeocode(lat,lng)}},err=>{console.log("GPS:",err);if(!gpsCentered){gpsCentered=true;map.setView([50.06,19.94],15)}},CONFIG.gpsOptions);
let lastGeoTime=0;function reverseGeocode(lat,lng){fetch(CONFIG.nominatimUrl+'?format=json&lat='+lat+'&lon='+lng+'&zoom=18&addressdetails=1').then(r=>r.json()).then(data=>{if(data&&data.address){const street=data.address.road||data.address.pedestrian||'';const num=data.address.house_number||'';if(street)document.getElementById('topStreet').textContent=street+(num?' '+num:'')}}).catch(()=>{})}
function checkRouteProximity(lat,lng){if(!routeInstructions.length)return;let bestIdx=instructionIndex,bestD=Infinity;for(let i=instructionIndex;i<routeInstructions.length;i++){const d=haversine(lat,lng,routeInstructions[i].lat,routeInstructions[i].lng);if(d<bestD){bestD=d;bestIdx=i}}if(bestIdx>instructionIndex)instructionIndex=bestIdx;const inst=routeInstructions[instructionIndex];if(!inst)return;const dist=haversine(lat,lng,inst.lat,inst.lng),distStr=fmtDist(dist);let remain=0;for(let i=instructionIndex;i<routeInstructions.length-1;i++){remain+=haversine(routeInstructions[i].lat,routeInstructions[i].lng,routeInstructions[i+1].lat,routeInstructions[i+1].lng)}remain+=dist;let etaMin=0,etaStr='—:—';if(currentSpeed>2){etaMin=(remain/currentSpeed)*60;etaStr=fmtArrival(etaMin)}const isLast=inst.text==='Dotrzyj do celu';document.getElementById('topArrow').textContent=bearingToArrow(inst.bearing||0);const distParts=distStr.match(/^([\d,.]+)\s*(.*)$/)||[distStr,distStr,''];document.getElementById('topDistNum').textContent=distParts[1];document.getElementById('topDistUnit').textContent=distParts[2];document.getElementById('topStreet').textContent=inst.text||'—';document.getElementById('topBar').classList.add('show');if(instructionIndex+1<routeInstructions.length){const nxt=routeInstructions[instructionIndex+1],nxtDist=haversine(lat,lng,nxt.lat,nxt.lng);document.getElementById('ntArrow').textContent=bearingToArrow(nxt.bearing||0);document.getElementById('ntDist').textContent=fmtDist(nxtDist);document.getElementById('ntText').textContent=nxt.text;document.getElementById('nextTurnHint').classList.add('show')}else document.getElementById('nextTurnHint').classList.remove('show');document.getElementById('statDist').textContent=fmtDist(remain);document.getElementById('statDur').textContent=fmtDuration(etaMin);document.getElementById('speedBar').classList.add('show');document.getElementById('rightSidebar').classList.add('show');document.getElementById('sbDist').textContent=fmtDist(remain);document.getElementById('speedCluster').classList.add('show');for(let i=instructionIndex;i<routeInstructions.length;i++){const ri=routeInstructions[i],riDist=haversine(lat,lng,ri.lat,ri.lng);if(riDist<=CONFIG.preNotifyRange&&riDist>CONFIG.cameraNearRange&&ri.index!==instructionIndex&&!spoken500m.has(i)){spoken500m.add(i);speak(ri.text==='Dotrzyj do celu'?'Za 500 metrów dotrzesz do celu: '+(destinationName||'cel'):'Za 500 metrów, '+ri.text)}}if(nearestCameraDistance<=CONFIG.preNotifyRange&&nearestCameraDistance>CONFIG.cameraNearRange){for(const cam of routeCameras){const d=haversine(lat,lng,cam.lat,cam.lng);if(Math.abs(d-nearestCameraDistance)<0.001&&!spokenCameras500m.has(cam.name)){spokenCameras500m.add(cam.name);speak('Uwaga, za 500 metrów fotoradar, '+cam.limit+' kilometrów na godzinę');break}}}if(instructionIndex!==lastSpokenIdx){lastSpokenIdx=instructionIndex;speak(isLast?'Za '+distStr+' dotrzesz do celu: '+(destinationName||'cel'):'Za '+distStr+', '+inst.text)}}
function startNav(){const q=document.getElementById('dest').value;if(!q)return alert("Wpisz cel podróży");if(!userPos)return alert("Oczekiwanie na GPS…");showLoading('Wyznaczanie trasy...');fetch(CONFIG.nominatimUrl+'?format=json&q='+encodeURIComponent(q)).then(r=>r.json()).then(data=>{if(!data.length){hideLoading();return alert("Nie znaleziono")}destination=L.latLng(data[0].lat,data[0].lon);destinationName=data[0].display_name.split(',')[0]||q;drawRoute()}).catch(()=>{hideLoading();alert("Błąd połączenia")})}
function drawRoute(){if(routeLine){map.removeLayer(routeLine);routeLine=null}const exclude=[];if(avoidTolls)exclude.push('toll');if(avoidFerries)exclude.push('ferry');if(avoidHighways)exclude.push('motorway');const coords=userPos.lng+','+userPos.lat+';'+destination.lng+','+destination.lat;let url=CONFIG.osrmUrl+'/'+coords+'?overview=full&geometries=geojson&steps=true';if(exclude.length)url+='&exclude='+exclude.join(',');if(routeType==='short'||routeType==='eco')url+='&weight=shortest';fetch(url).then(r=>r.json()).then(data=>{hideLoading();if(data.code!=='Ok'||!data.routes||!data.routes.length)return alert("Nie udało się wyznaczyć trasy");const r=data.routes[0];totalRouteDist=r.distance/1000;routeCoords=r.geometry.coordinates.map(c=>({lat:c[1],lng:c[0]}));routeLine=L.polyline(routeCoords.map(c=>[c.lat,c.lng]),{color:'#2979ff',weight:6,opacity:0.85}).addTo(map);extractInstructionsFromSteps(r);loadRouteCameras();navigationActive=true;lastSpokenIdx=-1;instructionIndex=0;spoken500m=new Set();spokenCameras500m=new Set();closeMainMenu();speak('Nawigacja uruchomiona. Kieruj się do '+destinationName)}).catch(()=>{hideLoading();alert("Błąd połączenia z serwerem tras")})}
function extractInstructionsFromSteps(osrmRoute){routeInstructions=[];if(!osrmRoute.legs||!osrmRoute.legs.length)return;const leg=osrmRoute.legs[0];if(!leg.steps)return;for(const step of leg.steps){if(step.maneuver&&step.maneuver.location){const lng=step.maneuver.location[0],lat=step.maneuver.location[1],modifier=step.maneuver.modifier||'',type=step.maneuver.type||'';let text=step.name||'';if(type==='turn'){if(modifier==='left')text='Skręć w lewo'+(text?' w '+text:'');else if(modifier==='right')text='Skręć w prawo'+(text?' w '+text:'');else if(modifier==='slight left')text='Skręć lewo w lewo'+(text?' w '+text:'');else if(modifier==='slight right')text='Skręć lewo w prawo'+(text?' w '+text:'');else text='Skręć'+(text?' w '+text:'')}else if(type==='new name'||type==='continue')text=text||'Kontynuuj prosto';else if(type==='depart')text='Kieruj się '+bearingName(step.maneuver.bearing_after||0);else if(type==='arrive')text='Dotrzyj do celu';else if(type==='roundabout')text='Wjedź na rondo'+(text?' i jedź '+text:'');routeInstructions.push({lat,lng,bearing:step.maneuver.bearing_after||0,text,cumDist:(step.distance||0)/1000,index:Math.round((step.geometry?step.geometry.coordinates.length:0)/2)})}}if(!routeInstructions.length||routeInstructions[routeInstructions.length-1].text!=='Dotrzyj do celu'){const last=routeCoords[routeCoords.length-1];routeInstructions.push({lat:last.lat,lng:last.lng,bearing:0,text:'Dotrzyj do celu',cumDist:totalRouteDist,index:routeCoords.length-1})}}
function stopNav(){destination=null;destinationName='';navigationActive=false;routeInstructions=[];routeCoords=[];instructionIndex=0;lastSpokenIdx=-1;totalRouteDist=0;lastCameraSpoken=null;currentSpeedLimit=0;routeCameras=[];routePOIs=[];poiMarkers.forEach(m=>map.removeLayer(m));poiMarkers=[];if(routeLine){map.removeLayer(routeLine);routeLine=null}rotateMap(0);['topBar','speedBar','rightSidebar','speedCluster','cameraAlert','speedWarning','nextTurnHint'].forEach(id=>document.getElementById(id).classList.remove('show'));document.getElementById('sbTrack').querySelectorAll('.sidebar-strip-marker').forEach(m=>m.remove());document.getElementById('sbProgress').style.height='0%';if(window.speechSynthesis.speaking)window.speechSynthesis.cancel();document.getElementById('voiceToast').classList.remove('show');document.getElementById('persistentMenu').style.display='flex';speak("Nawigacja zatrzymana")}
if(!isNightMode)document.body.classList.add('day-mode');document.getElementById('dayNightToggle').classList.toggle('on',isNightMode);document.getElementById('voiceToggle').classList.toggle('on',voiceEnabled);document.getElementById('mapTilesToggle').classList.toggle('on',mapTilesEnabled);openMainMenu();
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
let wakeLock=null;async function requestWakeLock(){try{wakeLock=await navigator.wakeLock.request('screen')}catch(e){}}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&navigationActive)requestWakeLock()});
window.addEventListener('beforeunload',e=>{if(navigationActive){e.preventDefault();e.returnValue=''}});
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});